import type { Metadata } from "next";
import "./globals.css";
import AppLayout from "@/components/app-layout";

export const metadata: Metadata = {
	title: "Harry Cover",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<AppLayout>{children}</AppLayout>
			</body>
		</html>
	);
}
